import bcrypt from "bcrypt";
const data = {
  users: [
    {
      name: "Umesh",
      email: "admin@example.com",
      password: bcrypt.hashSync("umesh@123", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "john@example.com",
      password: bcrypt.hashSync("John@123", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 820,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 720,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 100,
      description: "high quality product",
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 920,
      countInStock: 0,
      brand: "Nike",
      rating: 4.8,
      numReviews: 80,
      description: "high quality product",
    },
    {
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 1020,
      countInStock: 30,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 700,
      countInStock: 0,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 820,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 120,
      description: "high quality product",
    },
  ],
};

export default data;
