const data={
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            categeory:'Shirts',
            image:'/images/p1.jpg',
            price:820,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high qulity product',
        },
        {
            _id:'2',
            name:'Adidas Fit Shirt',
            categeory:'Shirts',
            image:'/images/p2.jpg',
            price:720,
            countInStock:20,
            brand:'Adidas',
            rating:4.0,
            numReviews:100,
            description:'high qulity product',
        },
        {
            _id:'3',
            name:'Lacoste Free Shirt',
            categeory:'Shirts',
            image:'/images/p3.jpg',
            price:920,
            countInStock:0,
            brand:'Nike',
            rating:4.8,
            numReviews:80,
            description:'high qulity product',
        },
        {
            _id:'4',
            name:'Nike Slim Pant',
            categeory:'Pants',
            image:'/images/p4.jpg',
            price:1020,
            countInStock:30,
            brand:'Nike',
            rating:4.5,
            numReviews:14,
            description:'high qulity product',
        },
        {
            _id:'5',
            name:'Puma Slim Pant',
            categeory:'Pants',
            image:'/images/p5.jpg',
            price:700,
            countInStock:0,
            brand:'Puma',
            rating:4.5,
            numReviews:10,
            description:'high qulity product',
        },
        {
            _id:'6',
            name:'Adidas Fit Pant',
            categeory:'Pants',
            image:'/images/p6.jpg',
            price:820,
            countInStock:10,
            brand:'Adidas',
            rating:4.5,
            numReviews:120,
            description:'high qulity product',
        },
    ],
};

export default data;